name: estapar

services:
  db:
    container_name: db_estapar
    image: postgres:17.5-alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "3005:5432"

  adminer:
    container_name: adminer_estapar
    image: adminer:latest
    ports:
      - "3007:8080"
    depends_on:
      - db
    volumes:
      - ./data/adminer:/var/lib/adminer/data

networks:
  host:
    external: true