name: estapar

services:
  db:
    container_name: db_estapar
    image: postgres:17.5-alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "3005:5432"
    networks:
      - database

  adminer:
    container_name: adminer_estapar
    image: adminer:latest
    ports:
      - "3007:8080"
    depends_on:
      - db
    volumes:
      - ./data/adminer:/var/lib/adminer/data
    networks:
      - database

  simulator:
    container_name: simulator_estapar
    image: cfontes0estapar/garage-sim:1.0.0
    network_mode: host

  backend:
    container_name: backend_estapar
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    network_mode: host
    depends_on:
      - db
      - simulator

networks:
  database:
    driver: bridge